media:
  input: assets/images
  output: /assets/images

content:
  - name: products
    label: 🛒 Products (Live on Shop)
    type: collection
    path: _products
    filename: "{name}.md"
    view:
      fields: [name, price, type, order]
      primary: name
      sort: [order, name]
      default:
        sort: order
        order: asc
    fields:
      - name: identifier
        label: Identifier
        type: string
        description: "A unique ID for this product (e.g., shirt-dustwave, poster-sexpot). Use lowercase letters, numbers, and dashes only. No spaces!"
      - name: name
        label: Product Name
        type: string
        description: "The name customers will see (e.g., 'DUST WAVE T-Shirt', 'First Time Sexpot Poster')."
      - name: price
        label: Price ($)
        type: number
        description: "Price in dollars. Just the number, no $ sign (e.g., 25, 35, 6)."
      - name: image
        label: Product Image
        type: image
        options:
          path: ""
        description: "Upload or select an image. Uploads to /assets/images/. Best size: 1000x1000px (square) or 1000x1500px (portrait). PNG or JPG."
      - name: type
        label: Product Type
        type: select
        options:
          values:
            - value: shirt
              label: "Shirt (T-shirts with size selector XS-3XL)"
            - value: physical
              label: "Physical (Shippable items: mugs, posters, VHS, etc.)"
            - value: digital
              label: "Digital (Event tickets or downloads with price variants)"
            - value: sold-out
              label: "Sold Out (Stays on shop, buy button hidden)"
            - value: archive
              label: "⚠️ ARCHIVE — Moves to Out of Stock folder (save & wait 30 sec)"
        description: "Choose what kind of product this is."
      - name: event
        label: Event
        type: string
        default: dustwave
        hidden: true
      - name: order
        label: Display Order
        type: number
        default: 0
        description: |
          Controls position on the shop page. Lower numbers appear first.
          TIP: Use 10, 20, 30... so you can insert new products in between.
      - name: sizes
        label: Sizes (shirts only)
        type: select
        options:
          multiple: true
          values: [XS, S, M, L, XL, 2XL, 3XL]
        default: [XS, S, M, L, XL, 2XL, 3XL]
        description: "Only for 'shirt' products! Select which sizes are available. All sizes selected by default."
      - name: variants
        label: Ticket Options (digital products only)
        type: object
        list: true
        description: |
          Only fill this out for "digital" products like event tickets!
          Add different ticket tiers here (e.g., Standard Ticket $10, VIP $25).
          Leave empty for shirts and physical items.
        fields:
          - name: name
            label: Option Name
            type: string
            description: "What customers see in the dropdown (e.g., 'Standard Ticket', '2-Pack Bundle')."
          - name: price
            label: Price ($)
            type: number
            description: "Price for this option. Just the number, no $ sign."
          - name: sku
            label: SKU (optional)
            type: string
            description: "Internal tracking code (e.g., dancewave-std). Optional but helpful for records."
      - name: body
        label: Product Description (HTML)
        type: code
        options:
          language: html
        default: |
          <!-- 🎬 EVENT TEMPLATE (delete if not an event) -->
          <strong>Dust Wave</strong> presents ...
          <br>
          <h2>🎬 EVENT NAME 🎬</h2>
          <h3>At the Venue!</h3>
          Join us at <strong>the Guild Cinema (3405 Central Ave NE) on December 12th at 10:30pm</strong> for a screening of <a href="https://www.imdb.com/title/tt5765804/" target="_blank"><strong><i>Annihilation!</i></strong></a>
          <br><br>
          Also, a Dust Wave short film right before! And a merch giveaway too! 🎥 🎉
          <br><br>
          <strong>Doors open at 10:00pm, show starts at 10:30pm. All tickets are will call at the door.</strong>
          <br><br>
          <strong><i>See you there!</i></strong>

          <!-- 👕 SHIRT TEMPLATE (delete if not a shirt) -->
          Get your very own DUST WAVE T-Shirt! 100% cotton. Available in XS, S, M, L, XL, 2XL, 3XL.

          <!-- 📦 PHYSICAL PRODUCT TEMPLATES (delete if not applicable) -->
          24" X 36" glossy poster. Ships in a tube.

          27" X 40" poster commemorating Attack of the 50 Ft. Dust Wave!

          15 oz. glossy black mug with our mark and name. Suitable for any potable liquids.

          Get a 3-pack of branded latex condoms! <em>Dust Wave is not responsible for any unwanted pregnancies.</em>

          The full show on the only format that matters — VHS. Includes bonus features.
        description: |
          Delete the templates you don't need and edit the one you're using.
          HTML tags: <strong>bold</strong>, <em>italic</em>, <br> line break, <h2>Header</h2>, <a href="URL">link</a>

  - name: out-of-stock
    label: 📦 Out of Stock (Archived)
    type: collection
    path: out-of-stock
    filename: "{name}.md"
    view:
      fields: [name, type]
      primary: name
    fields:
      - name: identifier
        label: Identifier
        type: string
        description: "The product's unique ID. Don't change this!"
      - name: name
        label: Product Name
        type: string
        description: "The product name (keep for records)."
      - name: price
        label: Price ($)
        type: number
        description: "Original price (keep for records)."
      - name: image
        label: Product Image
        type: image
        options:
          path: ""
        description: "The product image (keep for records). Images stored in /assets/images/."
      - name: type
        label: Product Status
        type: select
        options:
          values:
            - value: shirt
              label: "Shirt"
            - value: physical
              label: "Physical"
            - value: digital
              label: "Digital"
            - value: sold-out
              label: "Sold Out"
            - value: unarchive
              label: "⚠️ UNARCHIVE — Restore to Products folder (save & wait 30 sec)"
        description: "To restore this product, select UNARCHIVE and save."
      - name: event
        label: Event
        type: string
        default: dustwave
        hidden: true
      - name: order
        label: Display Order
        type: number
        default: 0
        description: "Original display order. Keep this so the product returns to the right position when restored."
      - name: sizes
        label: Sizes (shirts only)
        type: select
        options:
          multiple: true
          values: [XS, S, M, L, XL, 2XL, 3XL]
        description: "Original sizes (keep for records)."
      - name: variants
        label: Ticket Options (keep for records)
        type: object
        list: true
        description: "Original ticket options. Keep these so they're preserved if you restore this product."
        fields:
          - name: name
            label: Option Name
            type: string
          - name: price
            label: Price ($)
            type: number
          - name: sku
            label: SKU
            type: string
      - name: body
        label: Product Description (HTML)
        type: code
        options:
          language: html
        description: |
          Original description (HTML). Keep this so it's preserved if you restore this product.
          Common tags: <strong>bold</strong>, <em>italic</em>, <br>, <h2>, <a href="URL">link</a>
